# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

pod 'Firebase/Auth'
pod 'GoogleSignIn'

target 'memoryGame' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for memoryGame

  target 'memoryGameTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'memoryGameUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
