# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

pod 'Firebase/Core'
pod 'Firebase/Auth'
pod 'GoogleSignIn'
pod 'Firebase/Database'
pod 'JSQMessagesViewController'

target 'memoryGame1' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for memoryGame1

  target 'memoryGame1Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'memoryGame1UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
